### ISSUE TITLE
Social Media

### ISSUE THREAD

**Issue by kevinmershon** [mershon-enterprises/website#4]
## Integration targets:
- [x] Facebook page
  - https://www.facebook.com/mershon.enterprises
  - for SEO and blog sharing
- [x] Google+
  - https://plus.google.com/118422838433657907306
  - for SEO and blog sharing
- [x] LinkedIn
  - https://www.linkedin.com/company/mershon-enterprises-llc
- [x] Blogspot
  - http://blog.mershon.enterprises
  - the purpose of the blog is SEO and demonstrating our involvement in the community

**Comment by devinleonhart** [comment]
@kevinmershon Given the minimal activity we had on the Slixbits blog, I'm hesitant to try for anything that periodically updates. Even twitter seems like overkill for our business model at the starting phase. I think we should wait until we feel we need to keep a core set of follower engaged before we move into that.

Facebook, probably. As all that one would do is allow Facebook's audience to funnel to our website, or act as the website's 'replacement' for people who basically only would find us there.

**Comment by kevinmershon** [comment]
@devleorepo The Slixbits blog was dead because the other owners wouldn't allow me to use overhead to pay for time spent researching and writing blogs, not because there wasn't good content to be blogged. Social media is a valuable marketing tool and we need to be utilizing it as effectively as we can afford.

**Comment by devinleonhart** [comment]
@kevinmershon The use of blogspot saves me a lot of work. Instead of implementing our own management of posts and archives, we could use the [blogspot API](https://developers.google.com/blogger/docs/3.0/reference/index) to populate a "mirror" on the MEC website that doesn't handle logins and post behavior, yet still lets customers see what we're doing from the MEC site.

Thoughts?
